all: build test10 test20 test100

build:
	javac NetworkFlow.java

test10:
	java NetworkFlow tests/networks_10vertices.txt

test20:
	java NetworkFlow tests/networks_20vertices.txt

test100:
	java NetworkFlow tests/networks_100vertices.txt
