all: build

build:
	javac IndependentSet.java

test10: test10a test10b

test25: test25a test25b test25c test25d

test50: test50a test50b test50c test50d

test75: test75a test75b test75c test75d

test100: test100a test100b test100c test100d

test10a:
	java IndependentSet test_in/indset_graphs_10a.txt > out
	vimdiff out test_out/indset_graphs_10a_output.txt

test10b:
	java IndependentSet test_in/indset_graphs_10b.txt > out
	vimdiff out test_out/indset_graphs_10b_output.txt

test25a:
	java IndependentSet test_in/indset_graphs_25a.txt > out
	vimdiff out test_out/indset_graphs_25a_output.txt

test25b:
	java IndependentSet test_in/indset_graphs_25b.txt > out
	vimdiff out test_out/indset_graphs_25b_output.txt

test25c:
	java IndependentSet test_in/indset_graphs_25c.txt > out
	vimdiff out test_out/indset_graphs_25c_output.txt

test25d:
	java IndependentSet test_in/indset_graphs_25d.txt > out
	vimdiff out test_out/indset_graphs_25d_output.txt

test50a:
	java IndependentSet test_in/indset_graphs_50a.txt > out
	vimdiff out test_out/indset_graphs_50a_output.txt

test50b:
	java IndependentSet test_in/indset_graphs_50b.txt > out
	vimdiff out test_out/indset_graphs_50b_output.txt

test50c:
	java IndependentSet test_in/indset_graphs_50c.txt > out
	vimdiff out test_out/indset_graphs_50c_output.txt

test50d:
	java IndependentSet test_in/indset_graphs_50d.txt > out
	vimdiff out test_out/indset_graphs_50d_output.txt

test75a:
	java IndependentSet test_in/indset_graphs_75a.txt > out
	vimdiff out test_out/indset_graphs_75a_output.txt

test75b:
	java IndependentSet test_in/indset_graphs_75b.txt > out
	vimdiff out test_out/indset_graphs_75b_output.txt

test75c:
	java IndependentSet test_in/indset_graphs_75c.txt > out
	vimdiff out test_out/indset_graphs_75c_output.txt

test75d:
	java IndependentSet test_in/indset_graphs_75d.txt > out
	vimdiff out test_out/indset_graphs_75d_output.txt

test100a:
	java IndependentSet test_in/indset_graphs_100a.txt > out
	vimdiff out test_out/indset_graphs_100a_output.txt

test100b:
	java IndependentSet test_in/indset_graphs_100b.txt > out
	vimdiff out test_out/indset_graphs_100b_output.txt

test100c:
	java IndependentSet test_in/indset_graphs_100c.txt > out
	vimdiff out test_out/indset_graphs_100c_output.txt

test100d:
	java IndependentSet test_in/indset_graphs_100d.txt > out
	vimdiff out test_out/indset_graphs_100d_output.txt
